POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "root6969420",
    "name": "Superuser",
    "password": "salainen"
}

###

GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "root6969420",
    "password": "salainen"
}
