name: Deployment Pipeline

on:
  push:
    branches: [main] # ROK

jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node_version: "20"
      - name: Create env file
        run: echo "${{ secrets.ENV }}" > ./server/.env
      - name: Install dependencies & build
        run: npm run --prefix server build
      - name: Lint client
        run: npm run --prefix client lint
      - name: Test e2e
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run --prefix ../server start:test
          wait-on: http://localhost:3001
          working-directory: ./client
      - name: Lint server
        run: npm run --prefix server lint
      - name: Test server
        run: npm run --prefix server test
      - name: Trigger render deployment
        if: ${{ github.event_name == 'push'  && !contains(join(github.event.commits.*.message), '#skip')  }}
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_API_KEY}}
